### ISSUE TITLE
Can't find Transaction history

### ISSUE THREAD

**Issue by 5nyper** [SeraphimSerapis/paypal-rest-node-sample#3]
Hello, Ive cloned your project, changed the API keys, and made a transaction using credit card but I cannot see the transaction in my sandbox side, and the transactions were successful.

any help?

**Comment by DimiTech** [comment]
Can't really help you with that? Did you solve your problem yet? If you have post it here so others can see it and close the issue, thanks :)

**Comment by 5nyper** [comment]
I have thank you :)

**Comment by DimiTech** [comment]
Awesome, can you share your solution to the problem here please, in case someone else runs into it in the future? Thank you :)

**Comment by 5nyper** [comment]
Sure, basically it wont show up in your sandbox transaction history, but in the facilitator account that paypal generates for you, so log into that account and you can see the transactions made

**Comment by DimiTech** [comment]
Cool, thanks for sharing!
